"""Billing domain — Stripe subscriptions and webhooks."""
from typing import Protocol, Any


class IBillingService(Protocol):
    async def create_checkout_session(self, user_id: str, price_id: str) -> str: ...
    async def get_subscription_status(self, user_id: str) -> dict[str, Any]: ...
    async def cancel_subscription(self, user_id: str) -> None: ...
