"""Analysis domain — lab analysis, insights, red flags, timeline, dashboard."""
from typing import Protocol, Any


class IAnalysisService(Protocol):
    async def extract_biomarkers(self, text: str, user_id: str) -> dict[str, Any]: ...
    async def get_insights(self, user_id: str) -> list[dict[str, Any]]: ...
    async def get_red_flags(self, user_id: str) -> list[dict[str, Any]]: ...
    async def get_timeline(self, user_id: str) -> list[dict[str, Any]]: ...
