"""CRM domain — practitioner clients, programs, questionnaires."""
from typing import Protocol, Any


class ICRMService(Protocol):
    async def list_clients(self, practitioner_id: str) -> list[dict[str, Any]]: ...
    async def get_client_detail(self, practitioner_id: str, client_id: str) -> dict[str, Any]: ...
    async def assign_program(self, practitioner_id: str, client_id: str, program_id: str) -> None: ...
