"""Protocol domain — health protocols, progress, symptoms, check-ins, questionnaires, assignments."""
from typing import Protocol, Any


class IProtocolService(Protocol):
    async def get_active_protocol(self, user_id: str) -> dict[str, Any]: ...
    async def record_symptom(self, user_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    async def record_checkin(self, user_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    async def get_progress(self, user_id: str) -> dict[str, Any]: ...
