import { useNavigate } from 'react-router-dom'
import Seo from '../components/Seo.jsx'
import Footer from '../components/landing/Footer.jsx'

function getLegalPagePadding() {
  if (typeof window === 'undefined') return '80px 24px'
  return window.innerWidth < 500 ? '40px 16px' : '80px 24px'
}

function Section({ title, children, tone = 'slate' }) {
  const titleColor = tone === 'emerald' ? 'var(--teal-700, #0F6E56)' : 'var(--gray-900, #1d1d1f)'
  return (
    <div>
      <h2 style={{ color: titleColor, fontSize: 20, fontWeight: 600, marginBottom: 10 }}>{title}</h2>
      <div style={{ color: 'var(--gray-700, #424245)', fontSize: 15, lineHeight: 1.75 }}>
        {children}
      </div>
    </div>
  )
}

function BulletList({ items }) {
  return (
    <ul style={{ paddingLeft: 20, display: 'grid', gap: 10, margin: 0 }}>
      {items.map((item) => (
        <li key={item}>{item}</li>
      ))}
    </ul>
  )
}

export default function LegalSafety() {
  const navigate = useNavigate()

  return (
    <div style={{
      minHeight: '100vh',
      background: 'var(--white, #ffffff)',
      color: 'var(--gray-900, #1d1d1f)',
      fontFamily: '-apple-system, BlinkMacSystemFont, "SF Premium Display", sans-serif',
      padding: getLegalPagePadding(),
      maxWidth: 760,
      margin: '0 auto',
    }}>
      <Seo
        title="Legal & Safety | VITALOOP"
        description="Draft legal and safety language for VITALOOP, including US/EU disclaimers, wellness boundary guidance, and dosage safety notes for counsel review."
        path="/legal-safety"
      />

      <button
        onClick={() => navigate('/')}
        style={{
          background: 'none', border: 'none', cursor: 'pointer',
          display: 'flex', alignItems: 'center', gap: 6,
          fontSize: 14, color: 'var(--teal-600, #0F6E56)',
          marginBottom: 48, padding: 0,
        }}
      >
        ← Back to VITALOOP
      </button>

      <h1 style={{ fontSize: 34, lineHeight: 1.2, fontWeight: 700, color: 'var(--gray-900, #1d1d1f)', marginBottom: 12 }}>Legal & Safety</h1>
      <p style={{ color: 'var(--gray-500, #6e6e73)', fontSize: 14, marginBottom: 32 }}>Draft for legal review, not final legal advice. Last updated: May 2026.</p>

      <section style={{ display: 'grid', gap: 28 }}>
        <div style={{ padding: 20, borderRadius: 20, background: '#f8fafc', border: '1px solid #e2e8f0' }}>
          <Section title="Purpose of this page" tone="emerald">
            <p style={{ margin: 0 }}>
              This page collects the current safety and claim-boundary language for review with counsel. It is intended to help align product, marketing, and compliance teams before any broader rollout.
            </p>
          </Section>
        </div>

        <Section title="US disclaimer draft">
          <BulletList
            items={[
              'VITALOOP provides wellness and educational decision support only. It is not a medical device, medical practice, diagnosis service, or treatment plan.',
              'All biomarker interpretations and protocol suggestions are informational and should be reviewed with a licensed healthcare professional before use.',
              'Exact dosage suggestions, supplement timing, and lifestyle recommendations may not be appropriate for every person; contraindications, medications, pregnancy, age, and medical history must be reviewed first.',
              'If a user has acute symptoms, abnormal findings, or a high-risk profile, they should seek evaluation from a qualified clinician or emergency services as appropriate.',
            ]}
          />
        </Section>

        <Section title="EU / UK disclaimer draft">
          <BulletList
            items={[
              'VITALOOP is a wellness and informational platform. It does not replace professional medical assessment, diagnosis, or treatment.',
              'Any guidance generated by the product should be treated as supportive information, not as a substitute for clinical judgment or regulated medical advice.',
              'Product claims and user-facing language should be reviewed for country-specific regulatory requirements before publication in the EU or UK.',
              'Supplement and dosage guidance may be subject to local rules, country-specific labeling standards, and professional oversight requirements.',
            ]}
          />
        </Section>

        <Section title="Dosage and safety language" tone="emerald">
          <p style={{ marginTop: 0 }}>
            The product may surface exact dosage suggestions, but those outputs should be framed as decision-support recommendations that require human review. The safety policy should explicitly mention contraindications, interaction checks, and escalation to a licensed clinician when the data is incomplete, conflicting, or high risk.
          </p>
        </Section>

        <Section title="Recommended counsel questions">
          <BulletList
            items={[
              'Do our public claims remain within wellness / decision-support boundaries in the US, EU, and UK?',
              'Should exact dosage language be softened or gated behind practitioner workflows in specific jurisdictions?',
              'What escalation wording is required for potential adverse events, pregnancy, chronic conditions, or medication conflicts?',
              'Which terms, layouts, or product flows should be revised before publication in regulated markets?',
            ]}
          />
        </Section>

        <Section title="Draft footer note">
          <p style={{ marginTop: 0 }}>
            VITALOOP is designed to support wellness decision-making, not to diagnose, treat, or prevent disease. Users should consult a qualified clinician for any medical decision or if they are unsure whether a recommendation is appropriate.
          </p>
        </Section>

        <Section title="Contact">
          <p style={{ marginTop: 0 }}>
            Legal review contact: <a href="mailto:legal@vitaloop.com" style={{ color: 'var(--teal-500)' }}>legal@vitaloop.com</a>
          </p>
        </Section>
      </section>

      <Footer />
    </div>
  )
}