import { useNavigate } from 'react-router-dom'

export default function Terms() {
  const navigate = useNavigate()
  return (
    <div style={{
      minHeight: '100vh',
      background: 'var(--white, #ffffff)',
      color: 'var(--gray-900, #1d1d1f)',
      fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", sans-serif',
      padding: '80px 24px',
      maxWidth: 720,
      margin: '0 auto',
    }}>
      <button
        onClick={() => navigate('/')}
        style={{
          background: 'none', border: 'none', cursor: 'pointer',
          display: 'flex', alignItems: 'center', gap: 6,
          fontSize: 14, color: 'var(--teal-600, #0F6E56)',
          marginBottom: 48, padding: 0,
        }}
      >
        ← Back to VITALOOP
      </button>
      <h1 style={{ fontSize: 34, lineHeight: 1.2, fontWeight: 700, color: 'var(--gray-900, #1d1d1f)', marginBottom: 12 }}>Terms of Service</h1>
      <p style={{ color: 'var(--gray-500, #6e6e73)', fontSize: 14, marginBottom: 32 }}>Last updated: April 2026</p>

      <section style={{ display: 'grid', gap: 24, fontSize: 15, lineHeight: 1.7, color: 'var(--gray-700, #424245)' }}>
        <div>
          <h2 style={{ color: 'var(--gray-900, #1d1d1f)', fontSize: 20, fontWeight: 600, marginBottom: 8 }}>1. Acceptance</h2>
          <p>By using VITALOOP, you agree to these terms. If you do not agree, do not use the service.</p>
        </div>
        <div>
          <h2 style={{ color: 'var(--gray-900, #1d1d1f)', fontSize: 20, fontWeight: 600, marginBottom: 8 }}>2. Medical disclaimer</h2>
          <p><strong style={{ color: '#c62828' }}>VITALOOP is not a medical device, medical organization, or healthcare provider.</strong> The analysis and supplement protocols generated by our AI are for <strong>informational purposes only</strong> and do not constitute medical advice, diagnosis, or treatment. Always consult a licensed physician before making health decisions.</p>
        </div>
        <div>
          <h2 style={{ color: 'var(--gray-900, #1d1d1f)', fontSize: 20, fontWeight: 600, marginBottom: 8 }}>3. Subscription</h2>
          <p>Access to full features requires a paid subscription at $49/month. Subscriptions auto-renew monthly. You may cancel at any time from your account settings. No refunds are provided for partial months.</p>
        </div>
        <div>
          <h2 style={{ color: 'var(--gray-900, #1d1d1f)', fontSize: 20, fontWeight: 600, marginBottom: 8 }}>4. Acceptable use</h2>
          <p>You agree not to upload data that doesn't belong to you, attempt to reverse-engineer the service, or use VITALOOP for any illegal purpose.</p>
        </div>
        <div>
          <h2 style={{ color: 'var(--gray-900, #1d1d1f)', fontSize: 20, fontWeight: 600, marginBottom: 8 }}>5. Liability limitation</h2>
          <p>VITALOOP is provided "as is." We are not liable for any health outcomes, financial losses, or damages arising from use of this service. Your use is at your own risk.</p>
        </div>
        <div>
          <h2 style={{ color: 'var(--gray-900, #1d1d1f)', fontSize: 20, fontWeight: 600, marginBottom: 8 }}>6. Changes to terms</h2>
          <p>We may update these terms at any time. Continued use after changes constitutes acceptance.</p>
        </div>
        <div>
          <h2 style={{ color: 'var(--gray-900, #1d1d1f)', fontSize: 20, fontWeight: 600, marginBottom: 8 }}>7. Contact</h2>
          <p>Legal inquiries: <a href="mailto:legal@vitaloop.com" style={{ color: 'var(--teal-500)' }}>legal@vitaloop.com</a></p>
        </div>
      </section>
    </div>
  )
}
