import { useNavigate } from 'react-router-dom'

export default function Terms() {
  const navigate = useNavigate()
  return (
    <div className="min-h-screen bg-gray-950 text-gray-300 px-4 py-12 max-w-2xl mx-auto">
      <button onClick={() => navigate(-1)} className="text-green-400 text-sm mb-8 hover:underline">← Back</button>
      <h1 className="text-2xl font-bold text-white mb-6">Terms of Service</h1>
      <p className="text-gray-500 text-sm mb-8">Last updated: April 2026</p>

      <section className="space-y-6 text-sm leading-relaxed">
        <div>
          <h2 className="text-white font-semibold mb-2">1. Acceptance</h2>
          <p>By using VITALOOP, you agree to these terms. If you do not agree, do not use the service.</p>
        </div>
        <div>
          <h2 className="text-white font-semibold mb-2">2. Medical disclaimer</h2>
          <p><strong className="text-red-400">VITALOOP is not a medical device, medical organization, or healthcare provider.</strong> The analysis and supplement protocols generated by our AI are for <strong>informational purposes only</strong> and do not constitute medical advice, diagnosis, or treatment. Always consult a licensed physician before making health decisions.</p>
        </div>
        <div>
          <h2 className="text-white font-semibold mb-2">3. Subscription</h2>
          <p>Access to full features requires a paid subscription at $49/month. Subscriptions auto-renew monthly. You may cancel at any time from your account settings. No refunds are provided for partial months.</p>
        </div>
        <div>
          <h2 className="text-white font-semibold mb-2">4. Acceptable use</h2>
          <p>You agree not to upload data that doesn't belong to you, attempt to reverse-engineer the service, or use VITALOOP for any illegal purpose.</p>
        </div>
        <div>
          <h2 className="text-white font-semibold mb-2">5. Liability limitation</h2>
          <p>VITALOOP is provided "as is." We are not liable for any health outcomes, financial losses, or damages arising from use of this service. Your use is at your own risk.</p>
        </div>
        <div>
          <h2 className="text-white font-semibold mb-2">6. Changes to terms</h2>
          <p>We may update these terms at any time. Continued use after changes constitutes acceptance.</p>
        </div>
        <div>
          <h2 className="text-white font-semibold mb-2">7. Contact</h2>
          <p>Legal inquiries: <a href="mailto:legal@vitaloop.com" className="text-green-400 hover:underline">legal@vitaloop.com</a></p>
        </div>
      </section>
    </div>
  )
}
