"""Identity domain — auth, profile, onboarding."""
from typing import Protocol, Any


class IIdentityService(Protocol):
    async def get_profile(self, user_id: str) -> dict[str, Any]: ...
    async def update_profile(self, user_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    async def delete_account(self, user_id: str) -> None: ...
